# num datapts for training encoder, transition, classifier
num_pts: 5000

lx_path: /home/kensuke/latent-safety/logs/classifier/failure_set.pth
lx_img_path: /home/kensuke/latent-safety/logs/classifier_img/failure_set_img.pth
dyn_path: /home/kensuke/latent-safety/logs/dynamics/dynamics.pth
dyn_img_path: /home/kensuke/latent-safety/logs/dynamics_img/dynamics_img.pth
enc_img_path: /home/kensuke/latent-safety/logs/dynamics_img/encoder_img.pth
dyn_img_data: /home/kensuke/latent-safety/datasets/dyn_data.pkl
lx_img_data: /home/kensuke/latent-safety/datasets/classifier_data.pkl


# HJ computation bounds
x_min: -1.1
x_max: 1.1
y_min: -1.1
y_max: 1.1
dt: 0.05
numT: 100
nx: 101
ny: 101
nz: 101

obs_x: 0
obs_y: 0
obs_r: 0.5

# Dubins car parameters
u_max: 1.25
speed: 1
